version: '3.9'
services:
  db:
    restart: always
    image: postgres:15
    volumes:
      - //c/Program Files/PostgreSQL/15/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uhupup667
      POSTGRES_DB: books
      POSTGRES_HOST: db
    ports:
      - 5432:5432
    networks:
      - learning
  assignment3:
    build: ./
    command: ./Assignment3
    ports:
      - 8080:8080
    environment:
      - DB_URL=db:5432
    networks:
      - learning

networks:
  learning:
    driver: bridge